#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

URL="https://suitecrm.com/files/162/SuiteCRM-7.11/513/SuiteCRM-7.11.15.zip"
dl $URL /usr/local/src
