#!/bin/bash -e

VERSION=8.10.2
URL="https://github.com/SuiteCRM/SuiteCRM-Core/releases/download/v${VERSION}/SuiteCRM-${VERSION}.zip"
SHA256=ac4693d10ea2d6cd20b3256098781d134599d88878fb24e8dc127038d624f5a8
DEST="/usr/local/src/SuiteCRM-${VERSION}.zip"

proxy=()
if [ -n "${FAB_HTTP_PROXY:-}" ]; then
    proxy=(--proxy "$FAB_HTTP_PROXY")
fi

curl --fail --location --retry 3 --output "$DEST" "${proxy[@]}" "$URL"
echo "$SHA256  $DEST" | sha256sum --check --strict -
