#!/bin/sh -ex

DB_NAME=sugarcrm
DB_USER=sugarcrm
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey

SRC=/usr/local/src
WEBROOT=/var/www/sugarcrm

# unpack and configure
unzip $SRC/SugarCE-*.zip -d $SRC
rm $SRC/SugarCE-*.zip
mv $SRC/SugarCE-* $WEBROOT
chown -R root:root $WEBROOT

touch $WEBROOT/install.log
touch $WEBROOT/config_override.php

chown -R www-data:www-data $WEBROOT/cache
chown -R www-data:www-data $WEBROOT/custom
chown -R www-data:www-data $WEBROOT/modules
chown -R www-data:www-data $WEBROOT/upload
chown www-data:www-data $WEBROOT/config.php
chown www-data:www-data $WEBROOT/sugarcrm.log
chown www-data:www-data $WEBROOT/install.log
chown www-data:www-data $WEBROOT/config_override.php
chown www-data:www-data $WEBROOT/.htaccess

# php.ini tweaks
PHPINI=/etc/php5/apache2/php.ini
sed -i "s|^memory_limit.*|memory_limit = 256M|" $PHPINI
sed -i "s|^variables_order.*|variables_order = \"EGPCS\"|" $PHPINI
sed -i "s|^;date.timezone.*|date.timezone = \"UTC\"|" $PHPINI

# configure apache
a2dissite 000-default
a2ensite sugarcrm
a2enmod rewrite

# start services
/etc/init.d/mysql start
/etc/init.d/apache2 start

# curl based install
URL="http://127.0.0.1/install.php"
CURL="curl -c /tmp/cookie -b /tmp/cookie"

$CURL $URL --data "current_step=0&goto=Next&language=en_us"
$CURL $URL --data "current_step=1&goto=Next"
$CURL $URL --data "current_step=2&goto=Next&setup_license_accept=on"
$CURL $URL --data "current_step=3&goto=Next&install_type=custom"
$CURL $URL --data "current_step=4&goto=Next&setup_db_type=mysql"
$CURL $URL --data "checkDBSettings=true&to_pdf=1&sugar_body_only=1&setup_db_database_name=$DB_NAME&setup_db_host_name=localhost&setup_db_admin_user_name=root&setup_db_admin_password=$MYSQL_PASS&setup_db_sugarsales_user=&setup_db_sugarsales_password=&setup_db_sugarsales_password_retype=&dbUSRData=same&demoData=no&to_pdf=1&sugar_body_only=1"
$CURL $URL --data "current_step=5&goto=Next&setup_db_drop_tables=&setup_db_database_name=$DB_NAME&setup_db_host_name=localhost&setup_db_admin_user_name=root&setup_db_admin_password_entry=$MYSQL_PASS&setup_db_admin_password=&dbUSRData=same&setup_db_sugarsales_user=&setup_db_sugarsales_password_entry=&setup_db_sugarsales_password=&setup_db_sugarsales_password=&setup_db_sugarsales_password_retype_entry=&setup_db_sugarsales_password_retype=&demoData=no"
$CURL $URL --data "current_step=6&goto=Next&setup_site_url=http%3A%2F%2F127.0.0.1&setup_system_name=TurnKey+SugarCRM&setup_db_collation=utf8_general_ci&setup_site_admin_user_name=$ADMIN_NAME&setup_site_admin_password=$ADMIN_PASS&setup_site_admin_password_retype=$ADMIN_PASS"
$CURL $URL --data "current_step=7&goto=Next&setup_site_session_path=&setup_site_log_dir=.&setup_site_guid="
$CURL $URL --data "current_step=8&goto=Next"
$CURL $URL --data "default_user_name=admin&next=Finish"

rm -f /tmp/cookie

# workaround installer bug (broken add user password check)
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"

$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

sed -i "s|'db_user_name.*|'db_user_name' => '$DB_USER',|" $WEBROOT/config.php
sed -i "s|'db_password.*|'db_password' => '$DB_PASS',|" $WEBROOT/config.php

# stop services
/etc/init.d/apache2 stop
/etc/init.d/mysql stop

# blank out logs
echo > $WEBROOT/install.log
echo > $WEBROOT/sugarcrm.log

# tweak permissions
chown root:root $WEBROOT/.htaccess
chmod 640 $WEBROOT/config.php

# setup cron
CRON_SUGARCRM=/etc/cron.hourly/sugarcrm
cat >$CRON_SUGARCRM<<EOF
#!/bin/bash -e
# Trigger sugarcrm cron

su www-data -c "cd /var/www/sugarcrm; php -f cron.php > /dev/null 2>&1"
EOF
chmod +x $CRON_SUGARCRM

