#!/bin/bash -e
# regenerate sugarcrm secrets and mysql password

. /etc/default/inithooks

CONF=/var/www/sugarcrm/config.php
sed -i "s|'generatepasswordtmpl.*|'generatepasswordtmpl' => '$(uuidgen)',|" $CONF
sed -i "s|'lostpasswordtmpl.*|'lostpasswordtmpl' => '$(uuidgen)',|" $CONF
sed -i "s|'unique_key.*|'unique_key' => '$(mcookie)',|" $CONF

PASSWORD=$(mcookie)
sed -i "s|'db_password.*|'db_password' => '$PASSWORD',|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=sugarcrm --pass="$PASSWORD"

