#!/bin/bash -e
# regenerate suitecrm secrets and mysql password

. /etc/default/inithooks

BASE_PATH=/var/www/suitecrm
CONF1=$BASE_PATH/public/legacy/config.php
sed -i "s|'generatepasswordtmpl.*|'generatepasswordtmpl' => '$(uuidgen)',|" $CONF1
sed -i "s|'lostpasswordtmpl.*|'lostpasswordtmpl' => '$(uuidgen)',|" $CONF1
sed -i "s|'factoremailtmpl.*|'factoremailtmpl' => '$(uuidgen)',|" $CONF1
sed -i "s|'unique_key.*|'unique_key' => '$(mcookie)',|" $CONF1
sed -i "s|'oauth2_encryption_key.*|'oauth2_encryption_key' => '$(openssl rand -base64 32)',|" $CONF1

# (re)set DB password
PASSWD=$(mcookie)
CONF2=$BASE_PATH/public/legacy/config_si.php
CONF3=$BASE_PATH/.env.local
sed -i "s|'db_password.*|'db_password' => '$PASSWD',|" $CONF1
sed -i "s|'setup_db_admin_password.*|'setup_db_admin_password' => '$PASSWD',|" $CONF2
sed -Ei "\|^DATABASE_URL=|s|(.*suitecrm:)[0-9a-z]+(@127.*)|\1$PASSWD\2|" $CONF3
$INITHOOKS_PATH/bin/mysqlconf.py --user=suitecrm --pass="$PASSWD"

# regenerate .env.local
echo 'DATABASE_URL="mysql://suitecrm:'"$PASSWD"'@127.0.0.1/suitecrm"' > "$BASE_PATH/.env.local"
